version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      # No need to check for updates more often than once a month
      interval: monthly
    reviewers:
      - Alex-302
      - scripthunter7

  # Maintain dependencies for NPM - typically AGLint updates
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    reviewers:
      - Alex-302
      - scripthunter7
