# https://github.com/AdguardTeam/AGLint#configuration
root: true
extends:
  - aglint:recommended
syntax:
  - AdGuard
rules:
  no-excluded-rules:
    - error
    - regexp-patterns:
        # Do not forget to escape special regex characters
        - staff-start\.com\/js\/track\/
        - minkou.jp\/js\/tracking\.js
        - global.telemetry.insights.video.a2z.com
