name: 🔞 Bug report (NSFW)
description: If you found something with AdGuard filters that we should know about (NSFW)
labels: ["Unsorted", "NSFW"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        It is highly recommended to use our [Web Reporting Tool](https://link.adtidy.org/forward.html?action=report&app=home&from=github) instead of creating an issue on GitHub.
        To avoid invalid reports, please check and confirm following checkboxes.
      options:
        - label: This site contains sexually explicit material, otherwise use our [regular form](./new?template=bug_report.yml);
          required: true
        - label: Filters were updated before reproducing an issue;
          required: true
        - label: AdGuard product version is up-to-date;
          required: true
        - label: Browser version is up-to-date;
          required: true
        - label: If the site or app is broken, disabling AdGuard protection resolves the issue.
          required: true

  - type: dropdown
    id: adguards
    attributes:
      label: AdGuard Product
      description: What product do you use?
      multiple: true
      options:
        - AdGuard Browser Extension
        - AdGuard Content Blocker
        - AdGuard CLI for Linux
        - AdGuard DNS
        - AdGuard for Android
        - AdGuard Mini for Android
        - AdGuard for iOS
        - AdGuard for Windows
        - AdGuard for Mac
        - AdGuard Mini for Mac
        - Other ad blocker
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: AdGuard Version
      description: What version of our software are you running?
      placeholder: For example, 8.1.0, 4.14.2 Beta 2, 2.20 Nightly 8
    validations:
      required: true

  - type: dropdown
    id: what-happened
    attributes:
      label: Problem Type
      description: What type of problem have you encountered? If the problem does not fall under any category that is listed here, please email support@adguard.com
      multiple: true
      options:
        - Missed ads or ad leftovers
        - Website or app doesn't work properly
        - AdGuard gets detected on a website
        - Social media buttons — share, like, tweet, etc.
        - Annoyances — pop-ups, cookie warnings, etc.
        - Missed analytics or tracker
        - Dangerous site
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browser(s) do you use?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Opera
        - Yandex Browser
        - Brave
        - Other (specify in comment below)
        - Problem is app-related, not site-related
    validations:
      required: true

  - type: dropdown
    id: browsers_type
    attributes:
      label: Device
      description: Which device do you use?
      multiple: false
      options:
        - Desktop
        - Mobile
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Where is the problem encountered?
      description: Enter the web address or affected application link.
      placeholder: For example, https://example.com/
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ‎‎‎‎‎‎‎‎

  - type: markdown
    attributes:
      value: "### What filters do you have enabled?"

  - type: markdown
    attributes:
      value: |
        Select enabled filters from the list, or enter URLs of any custom filters in the comment field below.

  - type: dropdown
    id: filters_adblock
    attributes:
      label: Ad Blocking
      multiple: true
      options:
        - AdGuard Base filter
        - AdGuard Mobile Ads filter
        - EasyList
    validations:
      required: false

  - type: dropdown
    id: filters_privacy
    attributes:
      label: Privacy
      multiple: true
      options:
        - AdGuard Tracking Protection filter
        - AdGuard Mail Tracking Protection filter
        - AdGuard URL Tracking filter
        - EasyPrivacy
        - Legitimate URL Shortener
        - Peter Lowe's Blocklist
        - Fanboy's Anti-Facebook List
    validations:
      required: false

  - type: dropdown
    id: filters_social
    attributes:
      label: Social
      multiple: true
      options:
        - AdGuard Social Media filter
        - Fanboy's Social Blocking List
    validations:
      required: false

  - type: dropdown
    id: filters_annoyances
    attributes:
      label: Annoyances
      multiple: true
      options:
        - AdGuard Cookie Notices filter
        - AdGuard Popups filter
        - AdGuard Mobile App Banners filter
        - AdGuard Other Annoyances filter
        - AdGuard Widgets filter
        - Adblock Warning Removal List
        - Fanboy's Annoyances
        - Web Annoyances Ultralist
        - EasyList Cookie List
        - Dandelion Sprout's Annoyances List
        - Stevo's AI Blocklist
    validations:
      required: false

  - type: dropdown
    id: filters_security
    attributes:
      label: Security
      multiple: true
      options:
        - Online Malicious URL Blocklist
        - Phishing URL Blocklist
        - Scam Blocklist by DurableNapkin
        - uBlock Origin – Badware risks
        - Dandelion Sprout's Anti-Malware List
    validations:
      required: false

  - type: dropdown
    id: filters_other
    attributes:
      label: Other
      multiple: true
      options:
        - Filter unblocking search ads and self-promotion
        - AdGuard Experimental filter
        - Fanboy's Anti-thirdparty Fonts
    validations:
      required: false

  - type: dropdown
    id: filters_dns
    attributes:
      label: DNS filters
      multiple: true
      options:
        - AdGuard DNS filter
    validations:
      required: false
      
  - type: dropdown
    id: filters_regional
    attributes:
      label: Language-specific
      multiple: true
      options:
        - AdGuard Russian filter
        - AdGuard German filter
        - AdGuard Japanese filter
        - AdGuard Dutch filter
        - AdGuard Spanish/Portuguese filter
        - AdGuard Turkish filter
        - AdGuard French filter
        - AdGuard Ukrainian filter
        - AdGuard Italian filter
        - AdGuard Polish filter
        - AdGuard Chinese filter
        - ABPindo
        - Bulgarian list
        - EasyList China
        - EasyList Czech and Slovak
        - EasyList Dutch
        - EasyList Germany
        - EasyList Hebrew
        - EasyList Italy
        - EasyList Lithuania
        - Latvian List
        - Liste AR
        - Liste FR
        - ROList
        - Icelandic ABP List
        - AdBlockID
        - Greek AdBlock Filter
        - EasyList Portuguese
        - EasyList Thailand
        - Hungarian filter
        - Xfiles
        - "RU AdList: Counters"
        - ABPVN List
        - Official Polish filters for AdBlock, uBlock Origin & AdGuard
        - Polish GDPR-Cookies Filters
        - Estonian List
        - CJX's Annoyances List
        - Polish Social Filters
        - filterslist-KO Classic filter list
        - xinggsf
        - EasyList Spanish
        - KAD - Anti-Scam
        - Adblock List for Finland
        - ROLIST2
        - Persian Blocker
        - road-block
        - Polish Annoyances Filters
        - Polish Anti Adblock Filters
        - Frellwit's Swedish Filter
        - YousList
        - EasyList Polish
        - Polish Anti-Annoying Special Supplement
        - Dandelion Sprout's Serbo-Croatian List
        - IndianList
        - Macedonian adBlock Filters
        - Dandelion Sprout's Nordic Filters
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ‎‎‎‎‎‎‎‎
  - type: dropdown
    id: stealth
    attributes:
      label: What Stealth Mode options do you have enabled?
      description: Select any of these options if you have them enabled in Stealth Mode
      multiple: true
      options:
        - Block trackers
        - Remove tracking parameters
        - Hide your search queries
        - Send Do-Not-Track signals
        - Self-destruction of third-party cookies
        - Self-destruction of first-party cookies
        - Disable cache for third-party requests
        - Block the third-party Authorization header
        - Block WebRTC
        - Block Push API
        - Block Location API
        - Hide your Referrer from third-parties (specify in comment below if a custom value is used)
        - Hide your User-Agent (specify in comment below if a custom value is used)
        - Mask your IP address (specify in comment below if a custom value is used)
        - Remove X-client-Data header from HTTP request
        - Protect from DPI

  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: |
        Describe the issue extensively unless it is absolutely clear from the screenshot what the problem is;
        You can also indicate any other information that you think the developers should know.
    validations:
      required: true

  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots explaining your problem.
        DO NOT upload screenshots with sexually explicit material on GitHub directly.
        Instead, upload it to a third-party image host and paste the URL below.
        Use `<details> </details>` tag to hide screenshots under the spoiler.
      placeholder: If applicable, add screenshots explaining your problem.
      value: |
          <details><summary>Screenshot 1</summary>
          <!-- Paste screenshot below. -->
          
          
          
          </details>
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree that...
      options:
        - label: This report does not contain private info
          required: true
        - label: I DID NOT upload screenshots with sexually explicit material on GitHub directly
          required: true
