blank_issues_enabled: false
contact_links:
  - name: Filters documentation
    url: https://kb.adguard.com/general/how-to-create-your-own-ad-filters
    about: How to create your own ad filters.
  - name: Report an issue using AdGuard
    url: https://kb.adguard.com/technical-support/reporting-tool
    about: The simplest and right way to report us about missed ads, broken sites etc.