name: 🌱 Feature request
description: If you know how AdGuard filters can be improved
labels: ["Feature Request"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this form!

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        Please answer the following questions for yourself before submitting the feature request.
      options:
        - label: I checked the documentation and found no answer;
          required: true
        - label: I checked to make sure that this issue has not already been filed;
          required: true
        - label: This is not an ad or bug report.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Issue Details
      description: What happened?
      placeholder: Is your feature request related to a problem? Please add a clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description:
      placeholder: Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Alternative Solution
      description:
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        Upvote [important issues](https://github.com/AdguardTeam/AdguardFilters/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+) with a :+1:
