name: Feature request
description: Suggest an idea for AdGuard Filters
labels: ["Feature Request"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        Please answer the following questions for yourself before submitting the feature request.
      options:
        - label: I checked the documentation and found no answer;
          required: true
        - label: I checked to make sure that this issue has not already been filed;
          required: true
        - label: This is not an ad/bug report.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      placeholder: |
          Is your feature request related to a problem?
          Please add a simple and clear description of the problem.
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: |
          Suggest a possible solution in a clear and concise manner.
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      placeholder: |
          Add any other context about the problem here.
    validations:
      required: false