#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# TODO: Remove first 2 lines: https://github.com/AdguardTeam/AdguardFilters/pull/171886#issuecomment-1918731193

# See https://git-scm.com/docs/githooks#_pre_commit

npx lint-staged
