name: AGLint

on:
  push:
    branches:
      - master
    paths:
      - '**/*.txt'
  pull_request:
    branches:
      - master
    types:
      - opened
    paths:
      - '**/*.txt'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
    
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run AGLint
        run: yarn lint

      - name: Conclusion
        # Run always, even if previous steps are skipped or failed
        if: ${{ always() && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: technote-space/workflow-conclusion-action@v3
      
      - name: Send Slack notifications on failure
        # Run only if previous steps are failed
        if: ${{ failure() && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: workflow, repo, message, commit, author, eventName, ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
